package com.example.redditaddon.model

data class AllAwarding(
    val award_sub_type: String,
    val award_type: String,
    val awardings_required_to_grant_benefits: Any,
    val coin_price: Int,
    val coin_reward: Int,
    val count: Int,
    val days_of_drip_extension: Int,
    val days_of_premium: Int,
    val description: String,
    val end_date: Any,
    val giver_coin_reward: Any,
    val icon_format: String,
    val icon_height: Int,
    val icon_url: String,
    val icon_width: Int,
    val id: String,
    val is_enabled: Boolean,
    val is_new: Boolean,
    val name: String,
    val penny_donate: Any,
    val penny_price: Int,
    val resized_icons: List<ResizedIcon>,
    val resized_static_icons: List<ResizedStaticIcon>,
    val start_date: Int,
    val static_icon_height: Int,
    val static_icon_url: String,
    val static_icon_width: Int,
    val sticky_duration_seconds: Any,
    val subreddit_coin_reward: Int,
    val subreddit_id: String,
    val tiers_by_required_awardings: Any
)